services:
  listener:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}

    volumes:
      - ${XDG_RUNTIME_DIR}/pulse/native:/run/pulse/native
      - /etc/machine-id:/etc/machine-id:ro
      - ./models:/models

    command: ["python", "-m", "vox.cli", "--model-dir", "/models"]
    
    # Will be ignored if not available
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
