services:
  listener:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}

    volumes:
      #- /run/user/1000/pulse/native:/run/pulse/native
      - ${XDG_RUNTIME_DIR}/pulse/native:/run/pulse/native
      - /etc/machine-id:/etc/machine-id:ro
      - ./models:/models

    #command: ["bash", "-c", "while true; do sleep 10; done"]
    command: ["python", "-m", "vox.cli", "--model-dir", "/models"]
      #  "--model", "base", "--lang", "de", 
      #  "--model-dir", "/models", 
      #  "--silence-threshold", "15", "--pre-buffer", "3", 
      #  "--warmup", "2", "--chunk-size", "512", 
      #  "--output-handler", "stdout"
    
    # Comment if there is no docker toolkit installed
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
